<?php defined("ACORN_EXECUTE") or die("Access Denied.");

include("acorn/global/admin-html-header.php");
// include html header
?>

<div class="container">

<h1 class="page-header text-center"><i class="fa fa-key"></i> New Authenticator Device</h1>

<?php echo $InfoMsg; ?>

<form action="<?php echo constant("BASE_URL"); ?>account/two_factor/add" method="post" class="form-horizontal">
<input type="hidden" name="SUBMITTED_FORM" value="TRUE"/>

<fieldset>

<?php

require_once 'acorn/plugins/2FA/GoogleAuthenticator.php';

$ga = new PHPGangsta_GoogleAuthenticator();

$Secret = $ga->createSecret();



$URI = urlencode("otpauth://totp/". $Email ."?secret=" . $Secret . "&issuer=Acorn+Bookings");

$QRURL = "https://chart.googleapis.com/chart?chs=150x150&cht=qr&chl=".$URI."&choe=UTF-8";
?>

<p>1. Install <a href="https://support.google.com/accounts/answer/1066447" target="_blank">Google Authenticator</a></p>

<p>2. Use the app or a QR scanner to scan the code below:</p>
   
<img src="<?php echo $QRURL; ?>"/>

<p>3. Enter the code generated by the app in the box below</p>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="CurrentPassword">Code generated by app:</label>  
  <div class="col-md-5">
  <input name="Code" type="number" class="form-control input-md">
  <span class="help-block" style="color:red;"><?php echo $CurrentPasswordErr; ?></span>  
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="CurrentPassword">Label for device:</label>  
  <div class="col-md-5">
  <input name="Code" type="number" class="form-control input-md" placeholder="My Apple iPhone 6 Plus">
  <span class="help-block" style="color:red;"><?php echo $CurrentPasswordErr; ?></span>  
  </div>
</div>

<p>4. Click add below</p>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="save"></label>
  <div class="col-md-4">
    <input type="submit" class="btn btn-success" value="Add Device"/>
  </div>
</div>


</fieldset>
</form>


<?php

include("acorn/global/admin-html-footer.php");
// include html footer

