<?php defined("ACORN_EXECUTE") or die("Access Denied.");

if ($_SERVER["REQUEST_METHOD"] == "POST") {

$AllClear = 0;

$Code = $_POST["Code"];
$Label = CleanData($_POST["Label"]);
$Secret = $_POST["Secret"];

require_once 'acorn/plugins/2FA/GoogleAuthenticator.php';

$ga = new PHPGangsta_GoogleAuthenticator();
$Check = $ga->verifyCode($Secret, $Code, 8);

if($Check == true)
{
die("Success");
}
else
{
die("Fail");
}

}


include("acorn/global/admin-html-header.php");
// include html header
?>

<div class="container">

<?php
define("Panel_Title", "Add a Two-Factor Device");
include("acorn/global/account-html-header.php");
?>

<?php echo $InfoMsg; ?>

<form action="<?php echo constant("BASE_URL"); ?>account/two_factor/add" method="post">
<input type="hidden" name="SUBMITTED_FORM" value="TRUE"/>

<?php

require_once 'acorn/plugins/2FA/GoogleAuthenticator.php';

$ga = new PHPGangsta_GoogleAuthenticator();

$Secret = $ga->createSecret();



$URI = urlencode("otpauth://totp/". $Email ."?secret=" . $Secret . "&issuer=Acorn+Bookings");

$QRURL = "https://chart.googleapis.com/chart?chs=150x150&cht=qr&chl=".$URI."&choe=UTF-8";
?>

<p>1. Install <a href="https://support.google.com/accounts/answer/1066447" target="_blank">Google Authenticator</a></p>

<p>2. Use the app or a QR scanner to scan the code below:</p>
   
<img src="<?php echo $QRURL; ?>"/>

<p>3. Enter the code generated by the app in the box below</p>

<!-- Text input-->
<div class="form-group">
  <label for="CurrentPassword">Code generated by app:</label>  
  <input name="Code" type="number" class="form-control">
  <span class="help-block" style="color:red;"><?php echo $CodeErr; ?></span>  
</div>

4. Give this device a custom name

<!-- Text input-->
<div class="form-group">
  <label for="CurrentPassword">Device Name:</label>  
  <input name="Code" type="number" class="form-control" placeholder="My iPhone 1">
  <span class="help-block" style="color:red;"><?php echo $LabelErr; ?></span>  
</div>

<input type="hidden" name="Secret" value="<?php echo $Secret; ?>"/>

<p>5. You're all set! Just click add below...</p>

<input type="submit" class="btn btn-success" value="Add Device"/>

</form>

<?php

include("acorn/global/account-html-footer.php");

include("acorn/global/admin-html-footer.php");
// include html footer

